### global rule ###
# all relative url begin with the '/' e.g. /jekyll/update/2015/01/08/welcome-to-jekyll.html 


# Site settings
title: Your awesome title
email: rainkin1993@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rainkin1993.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  rainkin1993




# Build settings
markdown: kramdown
